
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  'AppSidebar': typeof import("../../app/components/AppSidebar.vue")['default']
  'DataTable': typeof import("../../app/components/DataTable.vue")['default']
  'NavUser': typeof import("../../app/components/NavUser.vue")['default']
  'AvatarTest': typeof import("../../app/components/avatar/Avatar.test")['default']
  'Avatar': typeof import("../../app/components/avatar/Avatar.vue")['default']
  'AvatarVariants': typeof import("../../app/components/avatar/avatarVariants")['default']
  'BookmarksItem': typeof import("../../app/components/bookmarks/Item.vue")['default']
  'BookmarksColumns': typeof import("../../app/components/bookmarks/columns")['default']
  'Bookmarks': typeof import("../../app/components/bookmarks/index")['default']
  'TagTest': typeof import("../../app/components/tag/Tag.test")['default']
  'Tag': typeof import("../../app/components/tag/Tag.vue")['default']
  'TagVariants': typeof import("../../app/components/tag/tagVariants")['default']
  'NuxtWelcome': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/welcome.vue")['default']
  'NuxtLayout': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
  'NuxtErrorBoundary': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
  'ClientOnly': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/client-only")['default']
  'DevOnly': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/dev-only")['default']
  'ServerPlaceholder': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/server-placeholder")['default']
  'NuxtLink': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/nuxt-link")['default']
  'NuxtLoadingIndicator': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  'NuxtTime': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
  'NuxtRouteAnnouncer': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
  'NuxtImg': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
  'NuxtPicture': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
  'ShadBadge': typeof import("../../app/components/ui/badge/index")['Badge']
  'ShadBreadcrumb': typeof import("../../app/components/ui/breadcrumb/index")['Breadcrumb']
  'ShadBreadcrumbEllipsis': typeof import("../../app/components/ui/breadcrumb/index")['BreadcrumbEllipsis']
  'ShadBreadcrumbItem': typeof import("../../app/components/ui/breadcrumb/index")['BreadcrumbItem']
  'ShadBreadcrumbLink': typeof import("../../app/components/ui/breadcrumb/index")['BreadcrumbLink']
  'ShadBreadcrumbList': typeof import("../../app/components/ui/breadcrumb/index")['BreadcrumbList']
  'ShadBreadcrumbPage': typeof import("../../app/components/ui/breadcrumb/index")['BreadcrumbPage']
  'ShadBreadcrumbSeparator': typeof import("../../app/components/ui/breadcrumb/index")['BreadcrumbSeparator']
  'ShadButton': typeof import("../../app/components/ui/button/index")['Button']
  'ShadDropdownMenu': typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenu']
  'ShadDropdownMenuCheckboxItem': typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
  'ShadDropdownMenuContent': typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuContent']
  'ShadDropdownMenuGroup': typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuGroup']
  'ShadDropdownMenuItem': typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuItem']
  'ShadDropdownMenuLabel': typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuLabel']
  'ShadDropdownMenuRadioGroup': typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
  'ShadDropdownMenuRadioItem': typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
  'ShadDropdownMenuSeparator': typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSeparator']
  'ShadDropdownMenuShortcut': typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuShortcut']
  'ShadDropdownMenuSub': typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSub']
  'ShadDropdownMenuSubContent': typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSubContent']
  'ShadDropdownMenuSubTrigger': typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
  'ShadDropdownMenuTrigger': typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuTrigger']
  'ShadDropdownMenuPortal': typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuPortal']
  'ShadInput': typeof import("../../app/components/ui/input/index")['Input']
  'ShadSeparator': typeof import("../../app/components/ui/separator/index")['Separator']
  'ShadSheet': typeof import("../../app/components/ui/sheet/index")['Sheet']
  'ShadSheetClose': typeof import("../../app/components/ui/sheet/index")['SheetClose']
  'ShadSheetContent': typeof import("../../app/components/ui/sheet/index")['SheetContent']
  'ShadSheetDescription': typeof import("../../app/components/ui/sheet/index")['SheetDescription']
  'ShadSheetFooter': typeof import("../../app/components/ui/sheet/index")['SheetFooter']
  'ShadSheetHeader': typeof import("../../app/components/ui/sheet/index")['SheetHeader']
  'ShadSheetTitle': typeof import("../../app/components/ui/sheet/index")['SheetTitle']
  'ShadSheetTrigger': typeof import("../../app/components/ui/sheet/index")['SheetTrigger']
  'ShadSidebar': typeof import("../../app/components/ui/sidebar/index")['Sidebar']
  'ShadSidebarContent': typeof import("../../app/components/ui/sidebar/index")['SidebarContent']
  'ShadSidebarFooter': typeof import("../../app/components/ui/sidebar/index")['SidebarFooter']
  'ShadSidebarGroup': typeof import("../../app/components/ui/sidebar/index")['SidebarGroup']
  'ShadSidebarGroupAction': typeof import("../../app/components/ui/sidebar/index")['SidebarGroupAction']
  'ShadSidebarGroupContent': typeof import("../../app/components/ui/sidebar/index")['SidebarGroupContent']
  'ShadSidebarGroupLabel': typeof import("../../app/components/ui/sidebar/index")['SidebarGroupLabel']
  'ShadSidebarHeader': typeof import("../../app/components/ui/sidebar/index")['SidebarHeader']
  'ShadSidebarInput': typeof import("../../app/components/ui/sidebar/index")['SidebarInput']
  'ShadSidebarInset': typeof import("../../app/components/ui/sidebar/index")['SidebarInset']
  'ShadSidebarMenu': typeof import("../../app/components/ui/sidebar/index")['SidebarMenu']
  'ShadSidebarMenuAction': typeof import("../../app/components/ui/sidebar/index")['SidebarMenuAction']
  'ShadSidebarMenuBadge': typeof import("../../app/components/ui/sidebar/index")['SidebarMenuBadge']
  'ShadSidebarMenuButton': typeof import("../../app/components/ui/sidebar/index")['SidebarMenuButton']
  'ShadSidebarMenuItem': typeof import("../../app/components/ui/sidebar/index")['SidebarMenuItem']
  'ShadSidebarMenuSkeleton': typeof import("../../app/components/ui/sidebar/index")['SidebarMenuSkeleton']
  'ShadSidebarMenuSub': typeof import("../../app/components/ui/sidebar/index")['SidebarMenuSub']
  'ShadSidebarMenuSubButton': typeof import("../../app/components/ui/sidebar/index")['SidebarMenuSubButton']
  'ShadSidebarMenuSubItem': typeof import("../../app/components/ui/sidebar/index")['SidebarMenuSubItem']
  'ShadSidebarProvider': typeof import("../../app/components/ui/sidebar/index")['SidebarProvider']
  'ShadSidebarRail': typeof import("../../app/components/ui/sidebar/index")['SidebarRail']
  'ShadSidebarSeparator': typeof import("../../app/components/ui/sidebar/index")['SidebarSeparator']
  'ShadSidebarTrigger': typeof import("../../app/components/ui/sidebar/index")['SidebarTrigger']
  'ShadSkeleton': typeof import("../../app/components/ui/skeleton/index")['Skeleton']
  'ShadTable': typeof import("../../app/components/ui/table/index")['Table']
  'ShadTableBody': typeof import("../../app/components/ui/table/index")['TableBody']
  'ShadTableCaption': typeof import("../../app/components/ui/table/index")['TableCaption']
  'ShadTableCell': typeof import("../../app/components/ui/table/index")['TableCell']
  'ShadTableEmpty': typeof import("../../app/components/ui/table/index")['TableEmpty']
  'ShadTableFooter': typeof import("../../app/components/ui/table/index")['TableFooter']
  'ShadTableHead': typeof import("../../app/components/ui/table/index")['TableHead']
  'ShadTableHeader': typeof import("../../app/components/ui/table/index")['TableHeader']
  'ShadTableRow': typeof import("../../app/components/ui/table/index")['TableRow']
  'ShadTagsInput': typeof import("../../app/components/ui/tags-input/index")['TagsInput']
  'ShadTagsInputInput': typeof import("../../app/components/ui/tags-input/index")['TagsInputInput']
  'ShadTagsInputItem': typeof import("../../app/components/ui/tags-input/index")['TagsInputItem']
  'ShadTagsInputItemDelete': typeof import("../../app/components/ui/tags-input/index")['TagsInputItemDelete']
  'ShadTagsInputItemText': typeof import("../../app/components/ui/tags-input/index")['TagsInputItemText']
  'ShadTooltip': typeof import("../../app/components/ui/tooltip/index")['Tooltip']
  'ShadTooltipContent': typeof import("../../app/components/ui/tooltip/index")['TooltipContent']
  'ShadTooltipProvider': typeof import("../../app/components/ui/tooltip/index")['TooltipProvider']
  'ShadTooltipTrigger': typeof import("../../app/components/ui/tooltip/index")['TooltipTrigger']
  'NuxtPage': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/pages/runtime/page")['default']
  'NoScript': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/head/runtime/components")['NoScript']
  'Link': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/head/runtime/components")['Link']
  'Base': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/head/runtime/components")['Base']
  'Title': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/head/runtime/components")['Title']
  'Meta': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/head/runtime/components")['Meta']
  'Style': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/head/runtime/components")['Style']
  'Head': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/head/runtime/components")['Head']
  'Html': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/head/runtime/components")['Html']
  'Body': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/head/runtime/components")['Body']
  'NuxtIsland': typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/nuxt-island")['default']
  'LazyAppSidebar': LazyComponent<typeof import("../../app/components/AppSidebar.vue")['default']>
  'LazyDataTable': LazyComponent<typeof import("../../app/components/DataTable.vue")['default']>
  'LazyNavUser': LazyComponent<typeof import("../../app/components/NavUser.vue")['default']>
  'LazyAvatarTest': LazyComponent<typeof import("../../app/components/avatar/Avatar.test")['default']>
  'LazyAvatar': LazyComponent<typeof import("../../app/components/avatar/Avatar.vue")['default']>
  'LazyAvatarVariants': LazyComponent<typeof import("../../app/components/avatar/avatarVariants")['default']>
  'LazyBookmarksItem': LazyComponent<typeof import("../../app/components/bookmarks/Item.vue")['default']>
  'LazyBookmarksColumns': LazyComponent<typeof import("../../app/components/bookmarks/columns")['default']>
  'LazyBookmarks': LazyComponent<typeof import("../../app/components/bookmarks/index")['default']>
  'LazyTagTest': LazyComponent<typeof import("../../app/components/tag/Tag.test")['default']>
  'LazyTag': LazyComponent<typeof import("../../app/components/tag/Tag.vue")['default']>
  'LazyTagVariants': LazyComponent<typeof import("../../app/components/tag/tagVariants")['default']>
  'LazyNuxtWelcome': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/welcome.vue")['default']>
  'LazyNuxtLayout': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
  'LazyNuxtErrorBoundary': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
  'LazyClientOnly': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/client-only")['default']>
  'LazyDevOnly': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/dev-only")['default']>
  'LazyServerPlaceholder': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
  'LazyNuxtLink': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/nuxt-link")['default']>
  'LazyNuxtLoadingIndicator': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
  'LazyNuxtTime': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
  'LazyNuxtRouteAnnouncer': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
  'LazyNuxtImg': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
  'LazyNuxtPicture': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
  'LazyShadBadge': LazyComponent<typeof import("../../app/components/ui/badge/index")['Badge']>
  'LazyShadBreadcrumb': LazyComponent<typeof import("../../app/components/ui/breadcrumb/index")['Breadcrumb']>
  'LazyShadBreadcrumbEllipsis': LazyComponent<typeof import("../../app/components/ui/breadcrumb/index")['BreadcrumbEllipsis']>
  'LazyShadBreadcrumbItem': LazyComponent<typeof import("../../app/components/ui/breadcrumb/index")['BreadcrumbItem']>
  'LazyShadBreadcrumbLink': LazyComponent<typeof import("../../app/components/ui/breadcrumb/index")['BreadcrumbLink']>
  'LazyShadBreadcrumbList': LazyComponent<typeof import("../../app/components/ui/breadcrumb/index")['BreadcrumbList']>
  'LazyShadBreadcrumbPage': LazyComponent<typeof import("../../app/components/ui/breadcrumb/index")['BreadcrumbPage']>
  'LazyShadBreadcrumbSeparator': LazyComponent<typeof import("../../app/components/ui/breadcrumb/index")['BreadcrumbSeparator']>
  'LazyShadButton': LazyComponent<typeof import("../../app/components/ui/button/index")['Button']>
  'LazyShadDropdownMenu': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenu']>
  'LazyShadDropdownMenuCheckboxItem': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']>
  'LazyShadDropdownMenuContent': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuContent']>
  'LazyShadDropdownMenuGroup': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuGroup']>
  'LazyShadDropdownMenuItem': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuItem']>
  'LazyShadDropdownMenuLabel': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuLabel']>
  'LazyShadDropdownMenuRadioGroup': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']>
  'LazyShadDropdownMenuRadioItem': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuRadioItem']>
  'LazyShadDropdownMenuSeparator': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSeparator']>
  'LazyShadDropdownMenuShortcut': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuShortcut']>
  'LazyShadDropdownMenuSub': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSub']>
  'LazyShadDropdownMenuSubContent': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSubContent']>
  'LazyShadDropdownMenuSubTrigger': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']>
  'LazyShadDropdownMenuTrigger': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuTrigger']>
  'LazyShadDropdownMenuPortal': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuPortal']>
  'LazyShadInput': LazyComponent<typeof import("../../app/components/ui/input/index")['Input']>
  'LazyShadSeparator': LazyComponent<typeof import("../../app/components/ui/separator/index")['Separator']>
  'LazyShadSheet': LazyComponent<typeof import("../../app/components/ui/sheet/index")['Sheet']>
  'LazyShadSheetClose': LazyComponent<typeof import("../../app/components/ui/sheet/index")['SheetClose']>
  'LazyShadSheetContent': LazyComponent<typeof import("../../app/components/ui/sheet/index")['SheetContent']>
  'LazyShadSheetDescription': LazyComponent<typeof import("../../app/components/ui/sheet/index")['SheetDescription']>
  'LazyShadSheetFooter': LazyComponent<typeof import("../../app/components/ui/sheet/index")['SheetFooter']>
  'LazyShadSheetHeader': LazyComponent<typeof import("../../app/components/ui/sheet/index")['SheetHeader']>
  'LazyShadSheetTitle': LazyComponent<typeof import("../../app/components/ui/sheet/index")['SheetTitle']>
  'LazyShadSheetTrigger': LazyComponent<typeof import("../../app/components/ui/sheet/index")['SheetTrigger']>
  'LazyShadSidebar': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['Sidebar']>
  'LazyShadSidebarContent': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarContent']>
  'LazyShadSidebarFooter': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarFooter']>
  'LazyShadSidebarGroup': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarGroup']>
  'LazyShadSidebarGroupAction': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarGroupAction']>
  'LazyShadSidebarGroupContent': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarGroupContent']>
  'LazyShadSidebarGroupLabel': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarGroupLabel']>
  'LazyShadSidebarHeader': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarHeader']>
  'LazyShadSidebarInput': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarInput']>
  'LazyShadSidebarInset': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarInset']>
  'LazyShadSidebarMenu': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenu']>
  'LazyShadSidebarMenuAction': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenuAction']>
  'LazyShadSidebarMenuBadge': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenuBadge']>
  'LazyShadSidebarMenuButton': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenuButton']>
  'LazyShadSidebarMenuItem': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenuItem']>
  'LazyShadSidebarMenuSkeleton': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenuSkeleton']>
  'LazyShadSidebarMenuSub': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenuSub']>
  'LazyShadSidebarMenuSubButton': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenuSubButton']>
  'LazyShadSidebarMenuSubItem': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenuSubItem']>
  'LazyShadSidebarProvider': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarProvider']>
  'LazyShadSidebarRail': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarRail']>
  'LazyShadSidebarSeparator': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarSeparator']>
  'LazyShadSidebarTrigger': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarTrigger']>
  'LazyShadSkeleton': LazyComponent<typeof import("../../app/components/ui/skeleton/index")['Skeleton']>
  'LazyShadTable': LazyComponent<typeof import("../../app/components/ui/table/index")['Table']>
  'LazyShadTableBody': LazyComponent<typeof import("../../app/components/ui/table/index")['TableBody']>
  'LazyShadTableCaption': LazyComponent<typeof import("../../app/components/ui/table/index")['TableCaption']>
  'LazyShadTableCell': LazyComponent<typeof import("../../app/components/ui/table/index")['TableCell']>
  'LazyShadTableEmpty': LazyComponent<typeof import("../../app/components/ui/table/index")['TableEmpty']>
  'LazyShadTableFooter': LazyComponent<typeof import("../../app/components/ui/table/index")['TableFooter']>
  'LazyShadTableHead': LazyComponent<typeof import("../../app/components/ui/table/index")['TableHead']>
  'LazyShadTableHeader': LazyComponent<typeof import("../../app/components/ui/table/index")['TableHeader']>
  'LazyShadTableRow': LazyComponent<typeof import("../../app/components/ui/table/index")['TableRow']>
  'LazyShadTagsInput': LazyComponent<typeof import("../../app/components/ui/tags-input/index")['TagsInput']>
  'LazyShadTagsInputInput': LazyComponent<typeof import("../../app/components/ui/tags-input/index")['TagsInputInput']>
  'LazyShadTagsInputItem': LazyComponent<typeof import("../../app/components/ui/tags-input/index")['TagsInputItem']>
  'LazyShadTagsInputItemDelete': LazyComponent<typeof import("../../app/components/ui/tags-input/index")['TagsInputItemDelete']>
  'LazyShadTagsInputItemText': LazyComponent<typeof import("../../app/components/ui/tags-input/index")['TagsInputItemText']>
  'LazyShadTooltip': LazyComponent<typeof import("../../app/components/ui/tooltip/index")['Tooltip']>
  'LazyShadTooltipContent': LazyComponent<typeof import("../../app/components/ui/tooltip/index")['TooltipContent']>
  'LazyShadTooltipProvider': LazyComponent<typeof import("../../app/components/ui/tooltip/index")['TooltipProvider']>
  'LazyShadTooltipTrigger': LazyComponent<typeof import("../../app/components/ui/tooltip/index")['TooltipTrigger']>
  'LazyNuxtPage': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/pages/runtime/page")['default']>
  'LazyNoScript': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/head/runtime/components")['NoScript']>
  'LazyLink': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/head/runtime/components")['Link']>
  'LazyBase': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/head/runtime/components")['Base']>
  'LazyTitle': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/head/runtime/components")['Title']>
  'LazyMeta': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/head/runtime/components")['Meta']>
  'LazyStyle': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/head/runtime/components")['Style']>
  'LazyHead': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/head/runtime/components")['Head']>
  'LazyHtml': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/head/runtime/components")['Html']>
  'LazyBody': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/head/runtime/components")['Body']>
  'LazyNuxtIsland': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/nuxt-island")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
