// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/pages/runtime/plugins/router.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/plugins/browser-devtools-timing.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/pages/runtime/plugins/check-if-page-unused.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+devtools@2.6.5_vite@7.1.10_@types+node@20.19.23_jiti@2.6.1_lightningcss@1.30.1_te_d9c1333e09eeeeadf64c2c0a5fc3e2e3/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+devtools@2.6.5_vite@7.1.10_@types+node@20.19.23_jiti@2.6.1_lightningcss@1.30.1_te_d9c1333e09eeeeadf64c2c0a5fc3e2e3/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/plugins/dev-server-logs.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/plugins/warn.dev.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/plugins/check-if-layout-used.js")> &
  InjectionType<typeof import("../../app/plugins/ssr-width")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'vue-devtools-client' | 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt:browser-devtools-timing' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'nuxt:global-components' | 'nuxt:prefetch' | 'nuxt:checkIfPageUnused' | 'nuxt:checkIfLayoutUsed'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
