
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const AppSidebar: typeof import("../app/components/AppSidebar.vue")['default']
export const DataTable: typeof import("../app/components/DataTable.vue")['default']
export const NavUser: typeof import("../app/components/NavUser.vue")['default']
export const AvatarTest: typeof import("../app/components/avatar/Avatar.test")['default']
export const Avatar: typeof import("../app/components/avatar/Avatar.vue")['default']
export const AvatarVariants: typeof import("../app/components/avatar/avatarVariants")['default']
export const BookmarksItem: typeof import("../app/components/bookmarks/Item.vue")['default']
export const BookmarksColumns: typeof import("../app/components/bookmarks/columns")['default']
export const Bookmarks: typeof import("../app/components/bookmarks/index")['default']
export const TagTest: typeof import("../app/components/tag/Tag.test")['default']
export const Tag: typeof import("../app/components/tag/Tag.vue")['default']
export const TagVariants: typeof import("../app/components/tag/tagVariants")['default']
export const NuxtWelcome: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const ShadBadge: typeof import("../app/components/ui/badge/index")['Badge']
export const ShadBreadcrumb: typeof import("../app/components/ui/breadcrumb/index")['Breadcrumb']
export const ShadBreadcrumbEllipsis: typeof import("../app/components/ui/breadcrumb/index")['BreadcrumbEllipsis']
export const ShadBreadcrumbItem: typeof import("../app/components/ui/breadcrumb/index")['BreadcrumbItem']
export const ShadBreadcrumbLink: typeof import("../app/components/ui/breadcrumb/index")['BreadcrumbLink']
export const ShadBreadcrumbList: typeof import("../app/components/ui/breadcrumb/index")['BreadcrumbList']
export const ShadBreadcrumbPage: typeof import("../app/components/ui/breadcrumb/index")['BreadcrumbPage']
export const ShadBreadcrumbSeparator: typeof import("../app/components/ui/breadcrumb/index")['BreadcrumbSeparator']
export const ShadButton: typeof import("../app/components/ui/button/index")['Button']
export const ShadDropdownMenu: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenu']
export const ShadDropdownMenuCheckboxItem: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
export const ShadDropdownMenuContent: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuContent']
export const ShadDropdownMenuGroup: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuGroup']
export const ShadDropdownMenuItem: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuItem']
export const ShadDropdownMenuLabel: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuLabel']
export const ShadDropdownMenuRadioGroup: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
export const ShadDropdownMenuRadioItem: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
export const ShadDropdownMenuSeparator: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSeparator']
export const ShadDropdownMenuShortcut: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuShortcut']
export const ShadDropdownMenuSub: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSub']
export const ShadDropdownMenuSubContent: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSubContent']
export const ShadDropdownMenuSubTrigger: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
export const ShadDropdownMenuTrigger: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuTrigger']
export const ShadDropdownMenuPortal: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuPortal']
export const ShadInput: typeof import("../app/components/ui/input/index")['Input']
export const ShadSeparator: typeof import("../app/components/ui/separator/index")['Separator']
export const ShadSheet: typeof import("../app/components/ui/sheet/index")['Sheet']
export const ShadSheetClose: typeof import("../app/components/ui/sheet/index")['SheetClose']
export const ShadSheetContent: typeof import("../app/components/ui/sheet/index")['SheetContent']
export const ShadSheetDescription: typeof import("../app/components/ui/sheet/index")['SheetDescription']
export const ShadSheetFooter: typeof import("../app/components/ui/sheet/index")['SheetFooter']
export const ShadSheetHeader: typeof import("../app/components/ui/sheet/index")['SheetHeader']
export const ShadSheetTitle: typeof import("../app/components/ui/sheet/index")['SheetTitle']
export const ShadSheetTrigger: typeof import("../app/components/ui/sheet/index")['SheetTrigger']
export const ShadSidebar: typeof import("../app/components/ui/sidebar/index")['Sidebar']
export const ShadSidebarContent: typeof import("../app/components/ui/sidebar/index")['SidebarContent']
export const ShadSidebarFooter: typeof import("../app/components/ui/sidebar/index")['SidebarFooter']
export const ShadSidebarGroup: typeof import("../app/components/ui/sidebar/index")['SidebarGroup']
export const ShadSidebarGroupAction: typeof import("../app/components/ui/sidebar/index")['SidebarGroupAction']
export const ShadSidebarGroupContent: typeof import("../app/components/ui/sidebar/index")['SidebarGroupContent']
export const ShadSidebarGroupLabel: typeof import("../app/components/ui/sidebar/index")['SidebarGroupLabel']
export const ShadSidebarHeader: typeof import("../app/components/ui/sidebar/index")['SidebarHeader']
export const ShadSidebarInput: typeof import("../app/components/ui/sidebar/index")['SidebarInput']
export const ShadSidebarInset: typeof import("../app/components/ui/sidebar/index")['SidebarInset']
export const ShadSidebarMenu: typeof import("../app/components/ui/sidebar/index")['SidebarMenu']
export const ShadSidebarMenuAction: typeof import("../app/components/ui/sidebar/index")['SidebarMenuAction']
export const ShadSidebarMenuBadge: typeof import("../app/components/ui/sidebar/index")['SidebarMenuBadge']
export const ShadSidebarMenuButton: typeof import("../app/components/ui/sidebar/index")['SidebarMenuButton']
export const ShadSidebarMenuItem: typeof import("../app/components/ui/sidebar/index")['SidebarMenuItem']
export const ShadSidebarMenuSkeleton: typeof import("../app/components/ui/sidebar/index")['SidebarMenuSkeleton']
export const ShadSidebarMenuSub: typeof import("../app/components/ui/sidebar/index")['SidebarMenuSub']
export const ShadSidebarMenuSubButton: typeof import("../app/components/ui/sidebar/index")['SidebarMenuSubButton']
export const ShadSidebarMenuSubItem: typeof import("../app/components/ui/sidebar/index")['SidebarMenuSubItem']
export const ShadSidebarProvider: typeof import("../app/components/ui/sidebar/index")['SidebarProvider']
export const ShadSidebarRail: typeof import("../app/components/ui/sidebar/index")['SidebarRail']
export const ShadSidebarSeparator: typeof import("../app/components/ui/sidebar/index")['SidebarSeparator']
export const ShadSidebarTrigger: typeof import("../app/components/ui/sidebar/index")['SidebarTrigger']
export const ShadSkeleton: typeof import("../app/components/ui/skeleton/index")['Skeleton']
export const ShadTable: typeof import("../app/components/ui/table/index")['Table']
export const ShadTableBody: typeof import("../app/components/ui/table/index")['TableBody']
export const ShadTableCaption: typeof import("../app/components/ui/table/index")['TableCaption']
export const ShadTableCell: typeof import("../app/components/ui/table/index")['TableCell']
export const ShadTableEmpty: typeof import("../app/components/ui/table/index")['TableEmpty']
export const ShadTableFooter: typeof import("../app/components/ui/table/index")['TableFooter']
export const ShadTableHead: typeof import("../app/components/ui/table/index")['TableHead']
export const ShadTableHeader: typeof import("../app/components/ui/table/index")['TableHeader']
export const ShadTableRow: typeof import("../app/components/ui/table/index")['TableRow']
export const ShadTagsInput: typeof import("../app/components/ui/tags-input/index")['TagsInput']
export const ShadTagsInputInput: typeof import("../app/components/ui/tags-input/index")['TagsInputInput']
export const ShadTagsInputItem: typeof import("../app/components/ui/tags-input/index")['TagsInputItem']
export const ShadTagsInputItemDelete: typeof import("../app/components/ui/tags-input/index")['TagsInputItemDelete']
export const ShadTagsInputItemText: typeof import("../app/components/ui/tags-input/index")['TagsInputItemText']
export const ShadTooltip: typeof import("../app/components/ui/tooltip/index")['Tooltip']
export const ShadTooltipContent: typeof import("../app/components/ui/tooltip/index")['TooltipContent']
export const ShadTooltipProvider: typeof import("../app/components/ui/tooltip/index")['TooltipProvider']
export const ShadTooltipTrigger: typeof import("../app/components/ui/tooltip/index")['TooltipTrigger']
export const NuxtPage: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyAppSidebar: LazyComponent<typeof import("../app/components/AppSidebar.vue")['default']>
export const LazyDataTable: LazyComponent<typeof import("../app/components/DataTable.vue")['default']>
export const LazyNavUser: LazyComponent<typeof import("../app/components/NavUser.vue")['default']>
export const LazyAvatarTest: LazyComponent<typeof import("../app/components/avatar/Avatar.test")['default']>
export const LazyAvatar: LazyComponent<typeof import("../app/components/avatar/Avatar.vue")['default']>
export const LazyAvatarVariants: LazyComponent<typeof import("../app/components/avatar/avatarVariants")['default']>
export const LazyBookmarksItem: LazyComponent<typeof import("../app/components/bookmarks/Item.vue")['default']>
export const LazyBookmarksColumns: LazyComponent<typeof import("../app/components/bookmarks/columns")['default']>
export const LazyBookmarks: LazyComponent<typeof import("../app/components/bookmarks/index")['default']>
export const LazyTagTest: LazyComponent<typeof import("../app/components/tag/Tag.test")['default']>
export const LazyTag: LazyComponent<typeof import("../app/components/tag/Tag.vue")['default']>
export const LazyTagVariants: LazyComponent<typeof import("../app/components/tag/tagVariants")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
export const LazyShadBadge: LazyComponent<typeof import("../app/components/ui/badge/index")['Badge']>
export const LazyShadBreadcrumb: LazyComponent<typeof import("../app/components/ui/breadcrumb/index")['Breadcrumb']>
export const LazyShadBreadcrumbEllipsis: LazyComponent<typeof import("../app/components/ui/breadcrumb/index")['BreadcrumbEllipsis']>
export const LazyShadBreadcrumbItem: LazyComponent<typeof import("../app/components/ui/breadcrumb/index")['BreadcrumbItem']>
export const LazyShadBreadcrumbLink: LazyComponent<typeof import("../app/components/ui/breadcrumb/index")['BreadcrumbLink']>
export const LazyShadBreadcrumbList: LazyComponent<typeof import("../app/components/ui/breadcrumb/index")['BreadcrumbList']>
export const LazyShadBreadcrumbPage: LazyComponent<typeof import("../app/components/ui/breadcrumb/index")['BreadcrumbPage']>
export const LazyShadBreadcrumbSeparator: LazyComponent<typeof import("../app/components/ui/breadcrumb/index")['BreadcrumbSeparator']>
export const LazyShadButton: LazyComponent<typeof import("../app/components/ui/button/index")['Button']>
export const LazyShadDropdownMenu: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenu']>
export const LazyShadDropdownMenuCheckboxItem: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']>
export const LazyShadDropdownMenuContent: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuContent']>
export const LazyShadDropdownMenuGroup: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuGroup']>
export const LazyShadDropdownMenuItem: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuItem']>
export const LazyShadDropdownMenuLabel: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuLabel']>
export const LazyShadDropdownMenuRadioGroup: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']>
export const LazyShadDropdownMenuRadioItem: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuRadioItem']>
export const LazyShadDropdownMenuSeparator: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSeparator']>
export const LazyShadDropdownMenuShortcut: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuShortcut']>
export const LazyShadDropdownMenuSub: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSub']>
export const LazyShadDropdownMenuSubContent: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSubContent']>
export const LazyShadDropdownMenuSubTrigger: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']>
export const LazyShadDropdownMenuTrigger: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuTrigger']>
export const LazyShadDropdownMenuPortal: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuPortal']>
export const LazyShadInput: LazyComponent<typeof import("../app/components/ui/input/index")['Input']>
export const LazyShadSeparator: LazyComponent<typeof import("../app/components/ui/separator/index")['Separator']>
export const LazyShadSheet: LazyComponent<typeof import("../app/components/ui/sheet/index")['Sheet']>
export const LazyShadSheetClose: LazyComponent<typeof import("../app/components/ui/sheet/index")['SheetClose']>
export const LazyShadSheetContent: LazyComponent<typeof import("../app/components/ui/sheet/index")['SheetContent']>
export const LazyShadSheetDescription: LazyComponent<typeof import("../app/components/ui/sheet/index")['SheetDescription']>
export const LazyShadSheetFooter: LazyComponent<typeof import("../app/components/ui/sheet/index")['SheetFooter']>
export const LazyShadSheetHeader: LazyComponent<typeof import("../app/components/ui/sheet/index")['SheetHeader']>
export const LazyShadSheetTitle: LazyComponent<typeof import("../app/components/ui/sheet/index")['SheetTitle']>
export const LazyShadSheetTrigger: LazyComponent<typeof import("../app/components/ui/sheet/index")['SheetTrigger']>
export const LazyShadSidebar: LazyComponent<typeof import("../app/components/ui/sidebar/index")['Sidebar']>
export const LazyShadSidebarContent: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarContent']>
export const LazyShadSidebarFooter: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarFooter']>
export const LazyShadSidebarGroup: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarGroup']>
export const LazyShadSidebarGroupAction: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarGroupAction']>
export const LazyShadSidebarGroupContent: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarGroupContent']>
export const LazyShadSidebarGroupLabel: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarGroupLabel']>
export const LazyShadSidebarHeader: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarHeader']>
export const LazyShadSidebarInput: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarInput']>
export const LazyShadSidebarInset: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarInset']>
export const LazyShadSidebarMenu: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarMenu']>
export const LazyShadSidebarMenuAction: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarMenuAction']>
export const LazyShadSidebarMenuBadge: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarMenuBadge']>
export const LazyShadSidebarMenuButton: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarMenuButton']>
export const LazyShadSidebarMenuItem: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarMenuItem']>
export const LazyShadSidebarMenuSkeleton: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarMenuSkeleton']>
export const LazyShadSidebarMenuSub: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarMenuSub']>
export const LazyShadSidebarMenuSubButton: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarMenuSubButton']>
export const LazyShadSidebarMenuSubItem: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarMenuSubItem']>
export const LazyShadSidebarProvider: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarProvider']>
export const LazyShadSidebarRail: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarRail']>
export const LazyShadSidebarSeparator: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarSeparator']>
export const LazyShadSidebarTrigger: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarTrigger']>
export const LazyShadSkeleton: LazyComponent<typeof import("../app/components/ui/skeleton/index")['Skeleton']>
export const LazyShadTable: LazyComponent<typeof import("../app/components/ui/table/index")['Table']>
export const LazyShadTableBody: LazyComponent<typeof import("../app/components/ui/table/index")['TableBody']>
export const LazyShadTableCaption: LazyComponent<typeof import("../app/components/ui/table/index")['TableCaption']>
export const LazyShadTableCell: LazyComponent<typeof import("../app/components/ui/table/index")['TableCell']>
export const LazyShadTableEmpty: LazyComponent<typeof import("../app/components/ui/table/index")['TableEmpty']>
export const LazyShadTableFooter: LazyComponent<typeof import("../app/components/ui/table/index")['TableFooter']>
export const LazyShadTableHead: LazyComponent<typeof import("../app/components/ui/table/index")['TableHead']>
export const LazyShadTableHeader: LazyComponent<typeof import("../app/components/ui/table/index")['TableHeader']>
export const LazyShadTableRow: LazyComponent<typeof import("../app/components/ui/table/index")['TableRow']>
export const LazyShadTagsInput: LazyComponent<typeof import("../app/components/ui/tags-input/index")['TagsInput']>
export const LazyShadTagsInputInput: LazyComponent<typeof import("../app/components/ui/tags-input/index")['TagsInputInput']>
export const LazyShadTagsInputItem: LazyComponent<typeof import("../app/components/ui/tags-input/index")['TagsInputItem']>
export const LazyShadTagsInputItemDelete: LazyComponent<typeof import("../app/components/ui/tags-input/index")['TagsInputItemDelete']>
export const LazyShadTagsInputItemText: LazyComponent<typeof import("../app/components/ui/tags-input/index")['TagsInputItemText']>
export const LazyShadTooltip: LazyComponent<typeof import("../app/components/ui/tooltip/index")['Tooltip']>
export const LazyShadTooltipContent: LazyComponent<typeof import("../app/components/ui/tooltip/index")['TooltipContent']>
export const LazyShadTooltipProvider: LazyComponent<typeof import("../app/components/ui/tooltip/index")['TooltipProvider']>
export const LazyShadTooltipTrigger: LazyComponent<typeof import("../app/components/ui/tooltip/index")['TooltipTrigger']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@20.19.23_@vue+compiler-sfc@3.5.22_db0@0.3._2b6ec9bbd5627e109add16b0c2a4641a/node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
